name: Dispatch new release

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: trtmn/homebrew-trtmn
        event-type: new_release
        client-payload: '{"version": "${{ github.event.release.tag_name }}"}'
